udpating clenv3

diff --git a/bin/experimental/clenv3 b/bin/experimental/clenv3
--- a/bin/experimental/clenv3
+++ b/bin/experimental/clenv3
@@ -8,7 +8,7 @@
 #
 
 # Safety First!
-set -ef
+set -efuC
 
 readonly scriptname="${0##*/}"
 
@@ -44,18 +44,21 @@ __clenv_default_vars=${SampShell_clenv_DEFAULTS_VARS-'TERM HOME SHLVL LANG'}
 usage () { cat; } <<USAGE
 usage: $scriptname [options] [--] [utility [argument ...]]
 options:
-    -D              Enables "dry mode"--don't actually run the program; Sets -V.
-    -V              Enables "verbose mode," so it prints out the invocation
-    -a              Pass _all_ environment variables in by default.
-    -n              Don't set any_arguments by default, including essential ones
-    -p              Shorthand for -vPATH
-    -P path         Use 'path' to find 'utility' \$PATH / -v supplied
-    -m pattern      Pass in any variables matching the awk pattern.
-    -v name[=value] Puts 'name' in the env of the called utility. If 'value' is
-                    omitted, it defaults to the current value of 'name' (which,
-                    if unset, is an error.)
+    -D              Don't actually run the program; Sets -V
+    -V              Print the invocation, and any changed variables.
+
+    -a              Pass all environment variables in by default.
+    -n, -i          Don't set any arguments by default, including essential ones
+    -P altpath      Use 'altpath' to find 'utility' instead of inherited \$PATH
+    -L              Lookup 'utility' using \$PATH (not working; do we want this?)
+
+    -v name[=value] Puts 'name' in the env of 'utility'. If 'value' is omitted,
+                    it uses the current value (or errors if unset).
+
     -u name         Unset 'name'. If both -v and -u are given, -u wins.
+    -m pattern      Pass in any variables matching the awk pattern.
     -_              Set the '_' variable in the env to the path to the executable
+    -p              Shorthand for -vPATH -P\$PATH
 
 "clean-env": A wrapper around 'env' which (by default) forwards a few essential
 arguments. Without arguments, prints out the variables
@@ -69,33 +72,55 @@ validate_variable_name () case $1 in
 		die 'invalid variable name (must match [\w_-]): %s' "$1" ;;
 esac
 
-while getopts 'hDV_anpP:m:v:u:U:' opt; do
+# Default the path to find the exe to `$PATH`
+__clenv_alt_path=
+__clenv_unset_vars=
+__clenv_dry=
+__clenv_verbose=
+__clenv_all_variables=
+__clenv_user_vars=
+
+while getopts 'hDV_anipP:m:v:u:U:' opt; do
 	case $opt in
 
 	h) usage; exit;;
 
 	# Dry mode and verbose mode. Enabling dry mode also enables verbose.
-	D) __clenv_dry=1 __clenv_verbose=1 ;;
-	V) __clenv_verbose=1 ;;
-	_) __clenv_underscore=1 ;;
+	D)
+		__clenv_dry=1 __clenv_verbose=1 ;;
+	V)
+		__clenv_verbose=1 ;;
+	_)
+		__clenv_underscore=1 ;;
+
+
+	p)
+		__clenv_default_vars="$__clenv_default_vars PATH"
+		__clenv_alt_path=$PATH ;;
+	P)
+		__clenv_alt_path=$OPTARG ;;
 
 	# Flags for specifying groups of variables to pass onwards.
 	a) __clenv_all_variables=1 __clenv_default_vars= ;;
-	n) __clenv_all_variables=  __clenv_default_vars= ;;
-	p) __clenv_default_vars="$__clenv_default_vars PATH" ;;
-	P) __clenv_alt_path=$OPTARG ;;
+	[ni]) __clenv_all_variables=  __clenv_default_vars= ;;
+
 	m) __clenv_default_vars="$__clenv_default_vars $(awk 'BEGIN {
 		for (k in ENVIRON) if(k ~ ARGV[1]) print k; exit }' "$OPTARG")";;
+
 	v)
+		# Fetch the name and optional value from the argument
 		__clenv_name=${OPTARG%=*}
 		__clenv_value=${OPTARG#"$__clenv_name"}
 
+		# Make sure the name is a valid name
 		validate_variable_name "$__clenv_name"
 
+		# If a value was given, use that.
 		if [ -n "$__clenv_value" ]; then
 			__clenv_value=${__clenv_value#=}
 		else
-			# TODO: ERR ON UNSET?
+			# Use the value in the environment; abort if not present.
+			eval '[ -z "${'$__clenv_name'+1}" ]' && die "variable $__clenv_name is unset."
 			eval "__clenv_value=\$$__clenv_name"
 		fi
 
@@ -114,8 +139,6 @@ while getopts 'hDV_anpP:m:v:u:U:' opt; do
 		# Unset it from the user vars
 		__clenv_user_vars=$(printf '%s' "$__clenv_user_vars" | \
 			sed "s/\"$OPTARG=\$__clenv_var_[0-9]*\"//1")
-		# __clenv_default_vars=$(printf '%s' "$__clenv_default_vars" | \
-		# 	sed "s/$OPTARG//1")
 		;;
 
 	U)
@@ -130,27 +153,52 @@ done
 ## Finish argument parsing.
 shift $(( OPTIND - 1 ))
 
-## Construct the command line
-__clenv_cmd="exec $(which env)"
+################################################################################
+#                          Construct the Command Line                          #
+################################################################################
+
+## The way `clenv` works is that we end up constructing a command line, then
+# execute it via `eval` later. The final command line looks like:
+# 	[PS4=; set -x;]      Print out invocation, for `-V``
+# 	[:]                  Don't actually run the `env` command, for `-D`
+#   exec                 Replace process with `exec`
+#   $(command -pv env)   Path that's guaranteed to have a POSIX-compliant `env`
+#   [-i]                 Set unless `-a` is passed, to remove all other vars
+#   [TERM=$TERM ...]     Default variables, if they're present, and `-n` not set
+#   [foo=bar ...]        user-defined variables to pass in
+#   --                   separator
+#   [/path/to/utility]   Looked up via `$PATH` / whatever `-P` sets
+#   [...]                arguments to utility
+##
+
+## We do a lot of checking for paths early on because we `unset` later
+
+# Initialize the command with `exec /path/to/env`
+__clenv_cmd="exec $(command -pv env)" || die 'unable to locate `env`'
+
+# Setup debug and verbose options
 [ -n "$__clenv_dry"     ]       && __clenv_cmd=": $__clenv_cmd"
 [ -n "$__clenv_verbose" ]       && __clenv_cmd="PS4=; set -x; $__clenv_cmd"
+
+# Unless `-a` was supplied, we clear away all other variables.
 [ -z "$__clenv_all_variables" ] && __clenv_cmd="$__clenv_cmd -i"
 
-## If any arguments are passed, then figure out the path to the executable. (We
-# need to do this, as `env` dictates if any of its args are `PATH=`, it'll use
-# _that_ as the path to search, which is not generally what I want when using
-# this command)
-if [ $# -ne 0 ]; then
-	# Ensure we find the program, as passing `PATH=` to env will overwrite it.
-	if ! __clenv_tmp=$(PATH=${__clenv_alt_path:-$PATH} command -v -- "$1"); then
+## If an alternative $PATH and utility were both supplied, then replace the
+# utility with the version we find.
+if [ $# -gt 0 ] && [ -n "$__clenv_alt_path" ]; then
+	# Find the path
+	if ! __clenv_utility_path=$(PATH=$__clenv_alt_path command -v -- "$1"); then
 		die 'unable to locate executable program: %s' "$1"
 	fi
 
-	if [ -n "$__clenv_underscore" ]; then
-		__clenv_cmd="\"_=$__clenv_tmp\""
-	fi
+	shift
+	set -- "$__clenv_utility_path" "$@"
+
+	# TODO: this is a vuln waiting to happen when the utility path has special chars
+	[ -n "$__clenv_underscore" ] && __clenv_cmd="$__clenv_cmd \"_=\$__clenv_utility_path\""
 fi
 
+## Unset variables we don't need
 __clenv_tmp=$(awk 'BEGIN {
 	for (k in ENVIRON) {
 		for (a in ARGV) {
@@ -166,9 +214,9 @@ fi
 unset -v -- $__clenv_tmp
 
 ## Add in default variables
-for __clenv_tmp in $__clenv_default_vars; do
-	if eval '[ -n "${'$__clenv_tmp'+1}" ]'; then
-		__clenv_cmd="$__clenv_cmd \"$__clenv_tmp=\$$__clenv_tmp\""
+for varname in $__clenv_default_vars; do
+	if eval '[ -n "${'$varname'+1}" ]'; then
+		__clenv_cmd="$__clenv_cmd \"$varname=\$$varname\""
 	fi
 done
 
@@ -176,4 +224,4 @@ done
 __clenv_cmd="$__clenv_cmd $__clenv_user_vars"
 
 ## Execute the command
-eval "$__clenv_cmd \"\$@\""
+eval "$__clenv_cmd -- \"\$@\""
