making mv-safe better

diff --git a/posix/non-interactive/bin/SampShell_mv-safe b/posix/non-interactive/bin/SampShell_mv-safe
--- a/posix/non-interactive/bin/SampShell_mv-safe
+++ b/posix/non-interactive/bin/SampShell_mv-safe
@@ -53,8 +53,6 @@ EOS
 rename_mode=
 clobber_empty=
 
-set -- 
-
 # Parse command line options
 while [ "$#" -ne 0 ]; do
    case "$1" in
@@ -89,62 +87,66 @@ done
 # If no arguments are given, then error out with the usage.
 [ "$#" -le 1 ] && shortusage
 
-echo "todo: rename_mode and clobber_empty"
-
+# Arg 1 is source, arg2 is destination
 try_move () {
-   if ! test -e "$1"
-   then
+   if [ ! -e "$1" ]; then
       printf >&2 '%s: cannot move %s: No such file or directory\n' "${scriptname}" "$1"
       return 1
    fi
 
-   # TODO: fix `\n` stuff
-   base="$(basename -- "$2"; echo .)"; base="${base%?.}"
-   stem="${base%%.*}"
-   ext="${base#"$stem"}"
-   root="$(dirname "$2")/$stem"
+   idx= target="$2"
 
-   idx=1
-   while test -e "$1"
-   do
-      if test "${idx}" -gt 1
-      then
-         target="${root} ${idx}${ext}"
-      else
-         target="${root}${ext}"
+   while
+      # Delete the target file/dir if it's empty.
+      if [ -n "${clobber_empty}" ]; then
+         if [ -f "${target}" ] && [ ! -s "${target}" ]; then
+            command -p rm -f -- "${target}" || return
+         elif [ -d "${target}" ] && ! ls -A1q -- "${target}" | grep -q .; then
+            command -p rm -fd -- "${target}" || return
+         fi
       fi
 
-      if test -e "${target}"
-      then
-         idx="$((idx+1))"
-         continue
-      fi
-
-      # try to move it in; if it doesn't succeed
-      # try to move the file into the target
+      # try to move the source file, returning an error if there's a problem.
       command -p mv -n -- "$1" "${target}" || return
+
+      # Now, after moving it, does it exist?
+      [ -e "$1" ]
+   do
+      # If we aren't renaming, and it exists, oops error!
+      [ -z "$rename_mode" ] && return 1
+
+      # If we haven't created an index, then setup all the arguments
+      if [ -z "$idx" ]; then
+         idx=1
+         base="$(basename -- "$2"; echo x)"; base="${base%?x}"
+         stem="${base%%.*}"
+         ext="${base#"$stem"}"
+         dir="$(dirname -- "$2"; echo x)"; dir="${dir%?x}"
+         root="$dir/$stem"
+      fi
+
+      # Now set the target and let's try again
+      target="$root $((idx=idx+1))$ext"
    done
+   return 0
 }
 
 # If two arguments are given, and the second isn't a directory, assume the first form
-if test "$#" -eq 2 && ! test -d "$2"
-then
+if [ "$#" -eq 2 ] && [ ! -d "$2" ]; then
    try_move "$1" "$2"
    exit
 fi
 
 # The target folder is the last argument; make sure it exists.
 target_folder=$(eval "echo \"\${$#}\"")
-if ! test -d "${target_folder}"
-then
-   printf >&2 '%s: cannot move files into %s: Not a directory\n' "${scriptname}" "${target_folder}"
-   exit 11
+if ! [ -d "${target_folder}" ]; then
+   die 11 'cannot move files into %s: Not a directory' "${target_folder}"
 fi
 
 last_status=0
-while test "$#" -gt 1
-do
-   try_move "$1" "${target_folder}/$(basename "$1")" || last_status=$?
+while [ "$#" -gt 1 ]; do
+   base="$(basename "$1"; echo x)"; base="${base%?x}"
+   try_move "$1" "$target_folder/$base" || last_status=$?
    shift
 done
 
