updatintg env and interactive

diff --git a/env b/env
--- a/env
+++ b/env
@@ -5,17 +5,21 @@
 # However, interactive shells should also `.` the `interactive` file as well,
 # after this one.
 #
+#
+# Overview
+# ========
 # This file does the following things:
 # 1. Check for `$SampShell_ROOTDIR` (see below
 # 2. Load the universal config for all POSIX-compliant shells
 # 3. Load shell-specific config
+#
 #
 # POSIX-compliant
 # ===============
 # Since this is the entry point for _all_ shells, it must be kept pristine and
 # strictly POSIX-compliant. Additionally, since it's expected that this file
 # might also be sourced from within a script at any point, options such as
-# `set -u nounset` must also be respected.
+# `set -o nounset` must also be respected.
 #
 #
 # $SampShell_ROOTDIR
@@ -25,16 +29,20 @@
 # to the folder that encloses this file. tl;dr, in the `~/.whatever`` file, put:
 #
 #   SampShell_ROOTDIR=/some/path/to/sampshell
-#   . "$SampShell_ROOTDIR/init"
+#   . "$SampShell_ROOTDIR/env"
 #
-# If it's not set, then it defaults to `$HOME/.sampshell`, and a warning is
-# emitted. (However, if zsh is detected---`ZSH_VERSION` exists---then the root
-# directory is inferred as `${0:P:h}`, and no warning is emitted.).
+# If `$SampShell_ROOTDIR` is not set, and we're not in an interactive shell (ie
+# `$-` doesn't contain `i`), then the script simply returns `1`. Otherwise, it
+# defaults to `$HOME/.sampshell` and emits a warning. As a special case, if zsh
+# is detected (by `$ZSH_VERSION` being nonempty), then `$SampShell_ROOTDIR` will
+# default to `${0:P:h}`, even in non-interactive shells, and no warnings/early
+# returns happen.
 #
-# Regardless of how `$SampShell_ROOTDIR` was set, if `$SampShell_ROOTDIR` does
-# not exist/isn't a directory, then an error message is printed and the rest of
-# the startup process is aborted.
+# If `$SampShell_ROOTDIR` isn't a directory (ie it points to a non-extant path,
+# or to a file), then the script returns 2 (printing an error if we're in an
+# interactive shell).
 #
+# If `$SampShell_ROOTDIR` is valid, then the rest of the script happens.
 ####
 
 ################################################################################
@@ -42,25 +50,34 @@
 ################################################################################
 
 # Make sure `SampShell_ROOTDIR` is set.
-if test -z "${SampShell_ROOTDIR-}"
-then
-	# If it's not set, and we're using ZSH, it's easy to find it.
-	if test -n "${ZSH_VERSION-}"
-	then
+if test -z "${SampShell_ROOTDIR-}"; then
+	# If we're using ZSH, just use the builtin `${0:P:h}` to find it.
+	if test -n "${ZSH_VERSION-}"; then
 		# We need to use `eval` in case shells don't understand `${0:P:h}`.
 		eval "SampShell_ROOTDIR=\"\${0:P:h}\""
+
+	# If we're not interactive, then just return 1
+	elif case $- in *i*) false; esac; then
+		return 1
+
+	# We are interactive, default it and warn
 	else
 		# Whelp, we can't rely on `$0`, let's just guess and hope?
 		SampShell_ROOTDIR="$HOME/.sampshell"
-		printf '[INFO] Defaulting $SampShell_ROOTDIR to %s\n' "$SampShell_ROOTDIR"
+		printf '[INFO] Defaulting $SampShell_ROOTDIR to %s\n' \
+			"$SampShell_ROOTDIR" >&2
 	fi
 fi
 
 # Make sure that it's actually a directory
 if ! test -d "$SampShell_ROOTDIR"
 then
-	printf '[FATAL] Unable to initialize SampShell: $SampShell_ROOTDIR does not exist/isnt a dir: %s\n' \
-		"${SampShell_ROOTDIR}" >&2
+	# If we're interactive, then print out the warning
+	if ! case $- in *i*) false; esac; then
+		printf '[FATAL] Unable to initialize SampShell: $SampShell_ROOTDIR does not exist/isnt a dir: %s\n' \
+			"${SampShell_ROOTDIR}" >&2
+	fi
+
 	return 1
 fi
 
