move pp to p, updated tcshrc

diff --git a/bin/universal/p b/bin/universal/p
--- a/bin/universal/p
+++ b/bin/universal/p
@@ -1,49 +1,175 @@
-#!/bin/sh
+#!/usr/bin/env -S ruby -Ebinary
 
-# Safety first, in the situation where we're `.`d.
-\unalias -a
-set -euf +xv
-unset -v IFS
+require 'optparse'
 
-# Escaped characters. Since we support shells that don't support POSIX-2024, we
-# can't use the `$'...'` syntax and need to use `printf` with escapes. A few
-# notes: The `\n`, `\r` and `\0` escapes have to be handled specially: \n and \r
-# can't be done directly with `$(...)` (`\r` is just a safeguard), and not all
-# shells support `\0`, so i do that here.
-nl=$(printf '\na') cr=$(printf '\ra') nul="$(printf \\0)"
-readonly nl="${nl%?}"         cr="${cr%?}"        nul="${nul:-a}" \
-         alrm="$(printf \\a)" bsp="$(printf \\b)" esc="$(printf \\e)" \
-         ff="$(printf \\f) "  tab="$(printf \\t)" vtab="$(printf \\v)"
+$isatty = $stdout.tty?
+OptParse.new do |op|
+  op.version = '1.0'
+  op.banner = <<~BANNER
+    usage: #{op.program_name} [options] [string ...]
+           #{op.program_name} -f [options] [file ...]
+    With no arguments, second form is assumed if stdin isnt a tty.
+  BANNER
 
-# Print out a character and escape
-presc () {
-	printf '\033[7m\\'${2-%s}'\033[27m' "$1"
-}
 
-argno=0
-for arg do
-	printf '%5d: ' $(( argno += 1 ))
+  op.separator "\nOptions"
 
-	# Check for length in case `arg` has `NUL` in it; we cant use `-z`.
-	while test ${#arg} -ne 0; do
-		tail=${arg#?}
-		head=${arg%"$tail"}
-		arg=$tail
+  op.on '-h', '--help', 'Print this and then exit' do puts op.help; exit end
+  op.on       '--version', 'Print the version' do puts op.ver; exit end
 
-		case $head in
-		[[:print:]]) printf %s "$head" ;;
-		$nul)        presc 0 ;; # `nul` defaults to `a`, which is `[[:print:]]`
-		$alrm)       presc a ;;
-		$bsp)        presc b ;;
-		$esc)        presc e ;;
-		$ff)         presc f ;;
-		$nl)         presc n ;;
-		$cr)         presc r ;;
-		$tab)        presc t ;;
-		$vtab)       presc v ;;
-		*)           presc "'$head" 'x%02X' ;;
-		esac
-	done
+  op.on '-f', '--files', 'Interpret arguments as filenames to be read instead of strings' do $files = true end
 
-	echo
-done
+  op.on '-N', '--[no-]number-args', "Number args; Not useful with -f. (default: when output's a tty)" do |nl| $number_lines = nl end
+  op.on       '--trailing-newline', 'Print a final trailing newline; only useful with -f. (default)' do $no_newline = false end
+  op.on '-n',  '--no-trailing-newline', 'Suppress final trailing newline.' do $no_newline = true end
+  # op.on '-N', '--[no-]number-lines', 'Number arguments; defaults to on when output is a TTY' do |nl| $number_lines = nl end
+
+  op.separator "\nWhat to Escape"
+  op.on       '--escape-newline', 'Escape newlines. (default)' do $escape_newline = true end
+  op.on '-l', '--no-escape-newline', "Don't escape newlines (\"Line-oriented mode\")" do $escape_newline = false end
+  op.on       '--escape-tab', 'Escape tabs. (default)' do $escape_tab = true end
+  op.on '-t', '--no-escape-tab', "Don't escape tabs" do $escape_tab = et end
+  op.on '-s', '--[no-]escape-space', 'Escape spaces; only useful when in visual mode.' do |es| $escape_space = es end
+  op.on       '--[no-]escape-outer-space', 'Like --escape-space, but only leading/trailing spaces',
+                                           'Not useful with -f. (default)' do |ess| $escape_surronding_spaces = ess end
+  op.on '-\\', '--[no-]escape-backslash', 'Escape backslashes (default: off when in --visual)' do |eb| $escape_backslash = eb end
+  op.on '-U', '--[no-]escape-unicode', 'Escape non-ASCII Unicode characters via `\u{...}`' do |eu| $escape_unicode = eu end
+  # op.on '-a', '--escape-all', 'Escapes all characters' do $escape_space = $escape_backslash = $escape_tab = $escape_newline = $escape_unicode = true end
+  # op.on '-w', '--no-escape-whitespace', 'Do not escape whitespace' do $escape_space = $escape_tab = $escape_newline = $escape_surronding_spaces = false end
+
+  op.on "\nHow to Escape"
+  $c_escapes = true
+  op.on '-v', '--visualize', 'Enable visual effects. (default: when output is a tty)' do $visual = true end
+  op.on '-V', '--no-visualize', "Don't enable visual effects" do $visual = false end
+  op.on       '--[no-]visualize-invalid', 'Enable a separator colour for invalid bytes when in visual mode',
+                                          'Not all output encodings have invalid bytes, eg -b. (default)' do |iv| $invalid_visual = iv end
+  op.on       '--c-escapes', 'Use C-style escapes (\n, \t, etc, and \xHH). (default)' do $c_escapes = true end
+  op.on '-x', '--hex-escapes', "Escape in \\xHH format. (doesn't affect backslashes or unicode)" do $c_escapes = false end
+  # TODO: octal?
+
+  op.on "\nOutput Encodings (all inputs are assumed binary)"
+  op.on '-E', '--encoding=ENCODING', 'The output encoding; Specify `list` for the list.' do |enc|
+    if enc == 'list'
+      puts "available encodings: #{(Encoding.name_list - %w[external internal]).join(', ')}"
+      exit
+    end
+
+    $encoding = Encoding.find enc rescue op.abort
+  end
+
+  op.on '-u', '-8', '--utf-8', 'Equivalent to --encoding=UTF-8. (default)' do $encoding = Encoding::UTF_8 end
+  op.on '-b', '--binary', '--bytes', 'Equivalent to --encoding=binary. (All bytes are valid.)' do $encoding = Encoding::BINARY end
+  op.on '-a', '--ascii', 'Equivalent to --encoding=ascii. (8th bit bytes are invalid.)' do $encoding = Encoding::ASCII end
+  op.on '-L', '--locale', 'Equivalent to --encoding=locale, i.e. what LC_ALL/LC_CTYPE/LANG specify.' do $encoding = Encoding.find('locale') end
+
+  op.on '--[no-]encoding-failure-err', 'Invalid bytes cause non-zero exit. (default: output isnt a tty)' do |efe| $encoding_failure_error = efe end
+
+  op.on_tail "\nnote: IF any invalid bytes for the output encoding are read, the exit status is based on `--encoding-failure-err`"
+
+  op.require_exact = true
+  op.on 'ENVIRONMENT: PP_BEGIN_STANDOUT; PP_END_STANDOUT; PP_BEGIN_ERR; PP_END_ERR'
+
+  op.parse! rescue op.abort # <-- only cares about flags when POSIXLY_CORRECT is set.
+  # op.order! rescue op.abort <-- does care about order of flags
+end
+
+BEGIN_STANDOUT = ENV.fetch('PP_BEGIN_STANDOUT', "\e[7m")
+END_STANDOUT   = ENV.fetch('PP_END_STANDOUT',   "\e[27m")
+BEGIN_ERR      = ENV.fetch('PP_BEGIN_ERR',      "\e[37m\e[41m")
+END_ERR        = ENV.fetch('PP_END_ERR',        "\e[49m\e[39m")
+
+$files = !$stdin.tty? if !defined?($files) && $*.empty?
+$visual = $stdout.tty? unless defined? $visual
+$encoding_failure_error = !$stdout.tty? unless defined? $visual
+$escape_spaces = !$files unless defined? $escape_spaces
+$escape_tab = true unless defined? $escape_tab
+$escape_newline = true unless defined? $escape_newline
+$number_lines = !$files && $stdout.tty? unless defined? $number_lines
+$encoding ||= Encoding.find('locale')
+$escape_backslash = !$visual unless defined? $escape_backslash
+$invalid_visual = true unless defined? $invalid_visual
+$escape_surronding_spaces = true unless defined? $escape_surronding_spaces
+OUTPUT = String.new(capacity: 4096 * 8)#, encoding: Encoding::BINARY)
+
+def vis_c(char, **b)
+  vis char.each_byte.map { |b| "\\x%02X" % b }.join, **b
+end
+
+def vis(val, alt=val, start: BEGIN_STANDOUT, stop: END_STANDOUT)
+  if $visual
+    "#{start}#{val}#{stop}"
+  else
+    alt
+  end
+end
+
+ESCAPES = Hash.new
+ESCAPES["\0"] = vis('\0') if $c_escapes
+ESCAPES["\n"] = "\n" unless $escape_newline
+ESCAPES["\t"] = "\t" unless $escape_tab
+
+$c_escapes and %W[\a \b \t \n \v \f \r \e].each do |chr|
+  ESCAPES[chr] ||= vis chr.inspect[1..-2]
+end
+
+# All the lower escapes that haven't been done yet
+(0x00...0x20).each { ESCAPES[_1.chr] ||= vis_c(_1.chr) }
+
+## Normal print characters
+(0x20..0x7F).map{ _1.chr $encoding }.each do |char|
+  ESCAPES[char] = char
+end
+ESCAPES["\\"] = vis("\\\\") if $escape_backslash
+ESCAPES[" "]  = vis(" ") if $escape_space
+
+# Upper bits, for binary encodings
+if $encoding == Encoding::BINARY
+  (0x80..0xFF).map{ _1.chr $encoding }.each do |char|
+    ESCAPES[char] = vis_c(char)
+  end
+end
+
+ESCAPES.default_proc = proc do |hash, char|
+  hash[char] = if !char.valid_encoding?
+    $ENCODING_FAILED = true
+    $invalid_visual ? vis_c(char, start: BEGIN_ERR, stop: END_ERR) : vis_c(char)
+  elsif $escape_unicode
+    vis('\u{%04X}' % char.codepoints.sum)
+  else
+    char
+  end
+end
+
+def handle(line)
+  line.each_char do |char|
+    OUTPUT.concat ESCAPES[char]
+  end
+end
+
+# TODO: allow for `pp filename`
+if !$files
+  $*.each_with_index do |arg, idx|
+    $number_lines and printf "%5d: ", idx += 1
+    arg = (+arg)
+    if $escape_surronding_spaces
+      arg.force_encoding 'binary'
+      x = arg.slice!(/\A */) and OUTPUT.concat vis(x)
+      rest = arg.slice!(/ *\z/)
+    end
+    handle arg.force_encoding $encoding
+    rest and OUTPUT.concat vis rest
+    OUTPUT.display
+    OUTPUT.clear
+    puts; $nl = true
+  end
+else
+  $<.binmode
+  while gets # TODO: handle directories
+    handle $_.force_encoding($encoding)
+    OUTPUT.display
+    OUTPUT.clear
+  end
+  puts unless $no_newline
+end
+
+exit 1 if $ENCODING_FAILED && $encoding_failure_error
