add teh ability to name multiple dirs to add-named-dir

diff --git a/zsh/functions/add-named-dir b/zsh/functions/add-named-dir
--- a/zsh/functions/add-named-dir
+++ b/zsh/functions/add-named-dir
@@ -2,32 +2,42 @@
 
 ##
 # Add a directory to the list of named directories.
-# (This file is really just a wrapper around `hash -d`)
+# (This file is really just a wrapper around `hash -d` with some error handling)
 ##
 
-emulate -L zsh # Reset ZSH to its default options, just for this function.
+emulate -L zsh -o EXTENDED_GLOB
 
-local dir name
-
-# Extract the name and directory from the arguments
-case $# in
-1) dir=$1; name=${dir:t} ;;
-2) dir=$2; name=$1 ;;
-*)
-	print >&2 "usage: $0 [name] dir"
+if (( $# == 0 )) then
+	print >&2 "usage: $0 [name=]dir [...]"
 	print >&2
 	print >&2 'Lets you use ~name as a shorthand for `dir`, eg `cd ~name/bar/baz`'
 	print >&2 'If `name` is not given, it defaults to the last part of `dir`'
 	return 1
-esac
-
-# Ensure a directory and name are actually given
-if [[ -z $dir ]] then
-	print >&2 -r -- "$0: an empty directory was given"
-	return 1
-elif [[ -z $name ]] then
-	print >&2 -r -- "$0: an empty name was given"
-	return 1
 fi
 
-builtin hash -d -- $name=$dir
+local arg
+local error=0
+
+for arg do
+	if [[ -z $arg ]] then
+		print >&2 -r -- "$0: empty argument ignored"; error=1
+	elif [[ $arg = \=* ]] then
+		print >&2 -r -- "$0: an empty name was given: ${(q)arg}"; error=1
+	elif [[ $arg = [-._[:alnum:]]##= ]] then
+		print >&2 -r -- "$0: an empty directory was given: ${(q)arg}"; error=1
+	else
+		if [[ $arg != [-._[:alnum:]]##=* ]] then
+			# To use the default name, the directory must end with only alnums, `_`, or
+			# a period. (Anything else won't be a valid directory name, so it'll fail.)
+			if [[ $arg != (*/|)[-._[:alnum:]]##(/|) ]]; then
+				print >&2 -r -- "$0: can't infer default name for: ${(q)arg}"; error=1
+				continue
+			fi
+			arg=${arg:t}=$arg
+		fi
+
+		builtin hash -d -- $arg
+	fi
+done
+
+return $error
