moved old stuff around, udpated trash to work

diff --git a/zsh/functions/add-named-dir b/zsh/functions/add-named-dir
--- a/zsh/functions/add-named-dir
+++ b/zsh/functions/add-named-dir
@@ -15,29 +15,34 @@ if (( $# == 0 )) then
 	return 1
 fi
 
-local arg
-local error=0
+local arg error=0
 
 for arg do
-	if [[ -z $arg ]] then
-		print >&2 -r -- "$0: empty argument ignored"; error=1
-	elif [[ $arg = \=* ]] then
-		print >&2 -r -- "$0: an empty name was given: ${(q)arg}"; error=1
-	elif [[ $arg = [-._[:alnum:]]##= ]] then
-		print >&2 -r -- "$0: an empty directory was given: ${(q)arg}"; error=1
-	else
-		if [[ $arg != [-._[:alnum:]]##=* ]] then
-			# To use the default name, the directory must end with only alnums, `_`, or
-			# a period. (Anything else won't be a valid directory name, so it'll fail.)
-			if [[ $arg != (*/|)[-._[:alnum:]]##(/|) ]]; then
-				print >&2 -r -- "$0: can't infer default name for: ${(q)arg}"; error=1
-				continue
-			fi
-			arg=${arg:t}=$arg
+	if [[ $arg != [-._[:alnum:]]##=* ]] then
+		if [[ -z $arg ]] then
+			print >&2 -r -- "$0: empty argument ignored"
+			error=1
+			continue
+		elif [[ $arg = \=* ]] then
+			print >&2 -r -- "$0: an empty name was given: ${(q)arg}"
+			error=1
+			continue
+		elif [[ $arg = [-._[:alnum:]]##= ]] then
+			print >&2 -r -- "$0: an empty directory was given: ${(q)arg}"
+			error=1
+			continue
+		# To use the default name, the directory must end with only alnums, `_`, or
+		# a period. (Anything else won't be a valid directory name, so it'll fail.)
+		elif  [[ $arg != (*/|)[-._[:alnum:]]##(/|) ]]; then
+			print >&2 -r -- "$0: can't infer default name for: ${(q)arg}"
+			error=1
+			continue
 		fi
 
-		builtin hash -d -- $arg
+		arg=${arg:t}=$arg
 	fi
+
+	builtin hash -d -- $arg
 done
 
 return $error
